const cards = {
  '7c': require('./7C.png'),
  '7d': require('./7D.png'),
  '7h': require('./7H.png'),
  '7s': require('./7S.png'),
  '8c': require('./8C.png'),
  '8d': require('./8D.png'),
  '8h': require('./8H.png'),
  '8s': require('./8S.png'),
  '9c': require('./9C.png'),
  '9d': require('./9D.png'),
  '9h': require('./9H.png'),
  '9s': require('./9S.png'),
  'tc': require('./10C.png'),
  'td': require('./10D.png'),
  'th': require('./10H.png'),
  'ts': require('./10S.png'),
  'jc': require('./JC.png'),
  'jd': require('./JD.png'),
  'jh': require('./JH.png'),
  'js': require('./JS.png'),
  'qc': require('./QC.png'),
  'qd': require('./QD.png'),
  'qh': require('./QH.png'),
  'qs': require('./QS.png'),
  'kc': require('./KC.png'),
  'kd': require('./KD.png'),
  'kh': require('./KH.png'),
  'ks': require('./KS.png'),
  'ac': require('./AC.png'),
  'ad': require('./AD.png'),
  'ah': require('./AH.png'),
  'as': require('./AS.png'),
  blue_back: require('./blue_back.png'),
  gray_back: require('./gray_back.png'),
  green_back: require('./green_back.png'),
  purple_back: require('./purple_back.png'),
  red_back: require('./red_back.png'),
  yellow_back: require('./yellow_back.png'),
};

export default cards;